eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 0
spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/products

management:
    endpoints:
      web:
        exposure:
            include: '*'
    tracing:
      sampling:
          probability: 1.0

