eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 0
    servlet:
        context-path: /
spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/products

management:
    endpoints:
      web:
        exposure:
            include: '*'
    tracing:
      sampling:
          probability: 1.0

openapi:
    service:
        title: product-service doc #title that you will want to display in the swagger ui
        version: 1.0.0
        url: http://localhost:8080 #api gateway url